### ISSUE TITLE
 'access denied bucket' error when linking minio

### ISSUE THREAD

**Issue by league3236** [okfn/ckanext-s3filestore#31]
Hi I am trying to link my personal minio through that extention.
I have no place to ask, so I leave here.

I tried to test the public minio first before linking it with the private minio.

minio url : http://play.min.io/

And I made a bucket.

bucket name : leaguetest

Changed the bucket to public.
```
./mc policy set public play/leaguetest/
```
Access permission for `play/leaguetest/` is set to `public`

```
[root@m01 minio]# ./mc policy set public play/leaguetest/
Access permission for `play/leaguetest/` is set to `public`
[root@m01 minio]# ./mc policy get play/leaguetest/
Access permission for `play/leaguetest/` is `public`
[root@m01 minio]#
[root@m01 minio]#
[root@m01 minio]# ./mc policy list play/leaguetest/
leaguetest/* => readwrite
```

The .ini file is set as follows:
```
ckanext.s3filestore.aws_access_key_id = Q3AM3UQ867SPQQA43P2F
ckanext.s3filestore.aws_secret_access_key = zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
ckanext.s3filestore.aws_bucket_name = leaguetest/
ckanext.s3filestore.host_name = http://play.min.io/
ckanext.s3filestore.region_name= us-east-1
ckanext.s3filestore.signature_version = s3v4
```

But I got the following error.
```
Traceback (most recent call last):
  File "/usr/local/bin/ckan-paster", line 8, in <module>
    sys.exit(run())
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/venv/src/ckan/ckan/lib/cli.py", line 357, in command
    self._load_config(cmd!='upgrade')
  File "/usr/lib/ckan/venv/src/ckan/ckan/lib/cli.py", line 330, in _load_config
    self.site_user = load_config(self.options.config, load_site_user)
  File "/usr/lib/ckan/venv/src/ckan/ckan/lib/cli.py", line 237, in load_config
    load_environment(conf.global_conf, conf.local_conf)
  File "/usr/lib/ckan/venv/src/ckan/ckan/config/environment.py", line 112, in load_environment
    p.load_all()
  File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 140, in load_all
    load(*plugins)
  File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 168, in load
    plugins_update()
  File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 122, in plugins_update
    environment.update_config()
  File "/usr/lib/ckan/venv/src/ckan/ckan/config/environment.py", line 288, in update_config
    plugin.configure(config)
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/ckanext/s3filestore/plugin.py", line 38, in configure
    ckanext.s3filestore.uploader.BaseS3Uploader().get_s3_bucket(
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/ckanext/s3filestore/uploader.py", line 29, in __init__
    self.bucket = self.get_s3_bucket(self.bucket_name)
  File "/usr/lib/ckan/venv/lib/python2.7/site-packages/ckanext/s3filestore/uploader.py", line 59, in get_s3_bucket
    'Access to bucket {0} denied'.format(bucket_name))
ckanext.s3filestore.uploader.S3FileStoreException: Access to bucket leaguetest denied
```

In the minio client, you can check that the upload is as follows.

```
./mc cp nohup.out play/leaguetest/
nohup.out:       788 B / 788 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 6.01 KiB/s 0s
```

How do I put a pemission policy on my minio client?

**Comment by ThrawnCA** [comment]
@league3236 I really hope that you've disabled the access key that you posted above, or else anyone who see this can access your account.
